And_Jang:
  admin:
    name: Fatou Dior DIOKHANE
    email: diokhane.fatou-dior@ugb.edu.sn
spring:
  application:
    name: And-Jang
  datasource:
    username: ${AND_JANG_DB_USER}
    password: ${AND_JANG_DB_PWD}
    url: ${AND_JANG_DB_URL}


  jpa:
    hibernate:
      #ddl-auto: create #### permet de supprimer toutes les tables et de les recr√©er
      ddl-auto: create
    show-sql: true